// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lidarws/src/main/resource/sensr_proto/point_cloud.proto

package sensr_proto;

public final class PointCloudOuterClass {
  private PointCloudOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensr_proto.PointResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    java.util.List<sensr_proto.PointCloudOuterClass.PointResult.PointCloud> 
        getPointsList();
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    sensr_proto.PointCloudOuterClass.PointResult.PointCloud getPoints(int index);
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    int getPointsCount();
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    java.util.List<? extends sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder> 
        getPointsOrBuilderList();
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder getPointsOrBuilder(
        int index);

    /**
     * <code>string uid = 201;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 201;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();
  }
  /**
   * Protobuf type {@code sensr_proto.PointResult}
   */
  public static final class PointResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensr_proto.PointResult)
      PointResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PointResult.newBuilder() to construct.
    private PointResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PointResult() {
      points_ = java.util.Collections.emptyList();
      uid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PointResult();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sensr_proto.PointCloudOuterClass.PointResult.class, sensr_proto.PointCloudOuterClass.PointResult.Builder.class);
    }

    public interface PointCloudOrBuilder extends
        // @@protoc_insertion_point(interface_extends:sensr_proto.PointResult.PointCloud)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
       * @return The type.
       */
      sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type getType();

      /**
       * <pre>
       * In calibration : algo_uid#topic, In runtime : meaningless
       * </pre>
       *
       * <code>string id = 2;</code>
       * @return The id.
       */
      java.lang.String getId();
      /**
       * <pre>
       * In calibration : algo_uid#topic, In runtime : meaningless
       * </pre>
       *
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <pre>
       * Data type of points is Vector3f(12bytes). When you parsing this data, please be aware of this.
       * </pre>
       *
       * <code>bytes points = 3;</code>
       * @return The points.
       */
      com.google.protobuf.ByteString getPoints();

      /**
       * <pre>
       * Data type of intensities is float(4bytes). When you parsing this data, please be aware of this.
       * </pre>
       *
       * <code>bytes intensities = 4;</code>
       * @return The intensities.
       */
      com.google.protobuf.ByteString getIntensities();
    }
    /**
     * Protobuf type {@code sensr_proto.PointResult.PointCloud}
     */
    public static final class PointCloud extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:sensr_proto.PointResult.PointCloud)
        PointCloudOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PointCloud.newBuilder() to construct.
      private PointCloud(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PointCloud() {
        type_ = 0;
        id_ = "";
        points_ = com.google.protobuf.ByteString.EMPTY;
        intensities_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PointCloud();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_PointCloud_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_PointCloud_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sensr_proto.PointCloudOuterClass.PointResult.PointCloud.class, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder.class);
      }

      /**
       * Protobuf enum {@code sensr_proto.PointResult.PointCloud.Type}
       */
      public enum Type
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>NONE = 0;</code>
         */
        NONE(0),
        /**
         * <code>GROUND = 1;</code>
         */
        GROUND(1),
        /**
         * <code>BACKGROUND = 2;</code>
         */
        BACKGROUND(2),
        /**
         * <code>RAW = 3;</code>
         */
        RAW(3),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>NONE = 0;</code>
         */
        public static final int NONE_VALUE = 0;
        /**
         * <code>GROUND = 1;</code>
         */
        public static final int GROUND_VALUE = 1;
        /**
         * <code>BACKGROUND = 2;</code>
         */
        public static final int BACKGROUND_VALUE = 2;
        /**
         * <code>RAW = 3;</code>
         */
        public static final int RAW_VALUE = 3;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Type valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static Type forNumber(int value) {
          switch (value) {
            case 0: return NONE;
            case 1: return GROUND;
            case 2: return BACKGROUND;
            case 3: return RAW;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            Type> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                public Type findValueByNumber(int number) {
                  return Type.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return sensr_proto.PointCloudOuterClass.PointResult.PointCloud.getDescriptor().getEnumTypes().get(0);
        }

        private static final Type[] VALUES = values();

        public static Type valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private Type(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:sensr_proto.PointResult.PointCloud.Type)
      }

      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_ = 0;
      /**
       * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override public sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type getType() {
        sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type result = sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type.forNumber(type_);
        return result == null ? sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type.UNRECOGNIZED : result;
      }

      public static final int ID_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object id_ = "";
      /**
       * <pre>
       * In calibration : algo_uid#topic, In runtime : meaningless
       * </pre>
       *
       * <code>string id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * In calibration : algo_uid#topic, In runtime : meaningless
       * </pre>
       *
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int POINTS_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString points_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Data type of points is Vector3f(12bytes). When you parsing this data, please be aware of this.
       * </pre>
       *
       * <code>bytes points = 3;</code>
       * @return The points.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPoints() {
        return points_;
      }

      public static final int INTENSITIES_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString intensities_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Data type of intensities is float(4bytes). When you parsing this data, please be aware of this.
       * </pre>
       *
       * <code>bytes intensities = 4;</code>
       * @return The intensities.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIntensities() {
        return intensities_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (type_ != sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type.NONE.getNumber()) {
          output.writeEnum(1, type_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
        }
        if (!points_.isEmpty()) {
          output.writeBytes(3, points_);
        }
        if (!intensities_.isEmpty()) {
          output.writeBytes(4, intensities_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (type_ != sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type.NONE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
        }
        if (!points_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, points_);
        }
        if (!intensities_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, intensities_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof sensr_proto.PointCloudOuterClass.PointResult.PointCloud)) {
          return super.equals(obj);
        }
        sensr_proto.PointCloudOuterClass.PointResult.PointCloud other = (sensr_proto.PointCloudOuterClass.PointResult.PointCloud) obj;

        if (type_ != other.type_) return false;
        if (!getId()
            .equals(other.getId())) return false;
        if (!getPoints()
            .equals(other.getPoints())) return false;
        if (!getIntensities()
            .equals(other.getIntensities())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getPoints().hashCode();
        hash = (37 * hash) + INTENSITIES_FIELD_NUMBER;
        hash = (53 * hash) + getIntensities().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(sensr_proto.PointCloudOuterClass.PointResult.PointCloud prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code sensr_proto.PointResult.PointCloud}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:sensr_proto.PointResult.PointCloud)
          sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_PointCloud_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_PointCloud_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  sensr_proto.PointCloudOuterClass.PointResult.PointCloud.class, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder.class);
        }

        // Construct using sensr_proto.PointCloudOuterClass.PointResult.PointCloud.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          type_ = 0;
          id_ = "";
          points_ = com.google.protobuf.ByteString.EMPTY;
          intensities_ = com.google.protobuf.ByteString.EMPTY;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_PointCloud_descriptor;
        }

        @java.lang.Override
        public sensr_proto.PointCloudOuterClass.PointResult.PointCloud getDefaultInstanceForType() {
          return sensr_proto.PointCloudOuterClass.PointResult.PointCloud.getDefaultInstance();
        }

        @java.lang.Override
        public sensr_proto.PointCloudOuterClass.PointResult.PointCloud build() {
          sensr_proto.PointCloudOuterClass.PointResult.PointCloud result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public sensr_proto.PointCloudOuterClass.PointResult.PointCloud buildPartial() {
          sensr_proto.PointCloudOuterClass.PointResult.PointCloud result = new sensr_proto.PointCloudOuterClass.PointResult.PointCloud(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(sensr_proto.PointCloudOuterClass.PointResult.PointCloud result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.type_ = type_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.id_ = id_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.points_ = points_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.intensities_ = intensities_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof sensr_proto.PointCloudOuterClass.PointResult.PointCloud) {
            return mergeFrom((sensr_proto.PointCloudOuterClass.PointResult.PointCloud)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(sensr_proto.PointCloudOuterClass.PointResult.PointCloud other) {
          if (other == sensr_proto.PointCloudOuterClass.PointResult.PointCloud.getDefaultInstance()) return this;
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (other.getPoints() != com.google.protobuf.ByteString.EMPTY) {
            setPoints(other.getPoints());
          }
          if (other.getIntensities() != com.google.protobuf.ByteString.EMPTY) {
            setIntensities(other.getIntensities());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  type_ = input.readEnum();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 18: {
                  id_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  points_ = input.readBytes();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 34: {
                  intensities_ = input.readBytes();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 34
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int type_ = 0;
        /**
         * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
         * @return The type.
         */
        @java.lang.Override
        public sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type getType() {
          sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type result = sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type.forNumber(type_);
          return result == null ? sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type.UNRECOGNIZED : result;
        }
        /**
         * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Type value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.sensr_proto.PointResult.PointCloud.Type type = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object id_ = "";
        /**
         * <pre>
         * In calibration : algo_uid#topic, In runtime : meaningless
         * </pre>
         *
         * <code>string id = 2;</code>
         * @return The id.
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * In calibration : algo_uid#topic, In runtime : meaningless
         * </pre>
         *
         * <code>string id = 2;</code>
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * In calibration : algo_uid#topic, In runtime : meaningless
         * </pre>
         *
         * <code>string id = 2;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          id_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * In calibration : algo_uid#topic, In runtime : meaningless
         * </pre>
         *
         * <code>string id = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          id_ = getDefaultInstance().getId();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * In calibration : algo_uid#topic, In runtime : meaningless
         * </pre>
         *
         * <code>string id = 2;</code>
         * @param value The bytes for id to set.
         * @return This builder for chaining.
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          id_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString points_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         * Data type of points is Vector3f(12bytes). When you parsing this data, please be aware of this.
         * </pre>
         *
         * <code>bytes points = 3;</code>
         * @return The points.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getPoints() {
          return points_;
        }
        /**
         * <pre>
         * Data type of points is Vector3f(12bytes). When you parsing this data, please be aware of this.
         * </pre>
         *
         * <code>bytes points = 3;</code>
         * @param value The points to set.
         * @return This builder for chaining.
         */
        public Builder setPoints(com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          points_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Data type of points is Vector3f(12bytes). When you parsing this data, please be aware of this.
         * </pre>
         *
         * <code>bytes points = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearPoints() {
          bitField0_ = (bitField0_ & ~0x00000004);
          points_ = getDefaultInstance().getPoints();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString intensities_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         * Data type of intensities is float(4bytes). When you parsing this data, please be aware of this.
         * </pre>
         *
         * <code>bytes intensities = 4;</code>
         * @return The intensities.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getIntensities() {
          return intensities_;
        }
        /**
         * <pre>
         * Data type of intensities is float(4bytes). When you parsing this data, please be aware of this.
         * </pre>
         *
         * <code>bytes intensities = 4;</code>
         * @param value The intensities to set.
         * @return This builder for chaining.
         */
        public Builder setIntensities(com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          intensities_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Data type of intensities is float(4bytes). When you parsing this data, please be aware of this.
         * </pre>
         *
         * <code>bytes intensities = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearIntensities() {
          bitField0_ = (bitField0_ & ~0x00000008);
          intensities_ = getDefaultInstance().getIntensities();
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:sensr_proto.PointResult.PointCloud)
      }

      // @@protoc_insertion_point(class_scope:sensr_proto.PointResult.PointCloud)
      private static final sensr_proto.PointCloudOuterClass.PointResult.PointCloud DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new sensr_proto.PointCloudOuterClass.PointResult.PointCloud();
      }

      public static sensr_proto.PointCloudOuterClass.PointResult.PointCloud getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PointCloud>
          PARSER = new com.google.protobuf.AbstractParser<PointCloud>() {
        @java.lang.Override
        public PointCloud parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<PointCloud> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PointCloud> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public sensr_proto.PointCloudOuterClass.PointResult.PointCloud getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int POINTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<sensr_proto.PointCloudOuterClass.PointResult.PointCloud> points_;
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    @java.lang.Override
    public java.util.List<sensr_proto.PointCloudOuterClass.PointResult.PointCloud> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    @java.lang.Override
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    @java.lang.Override
    public sensr_proto.PointCloudOuterClass.PointResult.PointCloud getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
     */
    @java.lang.Override
    public sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    public static final int UID_FIELD_NUMBER = 201;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uid_ = "";
    /**
     * <code>string uid = 201;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 201;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(1, points_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 201, uid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, points_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(201, uid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sensr_proto.PointCloudOuterClass.PointResult)) {
        return super.equals(obj);
      }
      sensr_proto.PointCloudOuterClass.PointResult other = (sensr_proto.PointCloudOuterClass.PointResult) obj;

      if (!getPointsList()
          .equals(other.getPointsList())) return false;
      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPointsCount() > 0) {
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getPointsList().hashCode();
      }
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sensr_proto.PointCloudOuterClass.PointResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sensr_proto.PointCloudOuterClass.PointResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sensr_proto.PointCloudOuterClass.PointResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sensr_proto.PointCloudOuterClass.PointResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensr_proto.PointResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensr_proto.PointResult)
        sensr_proto.PointCloudOuterClass.PointResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sensr_proto.PointCloudOuterClass.PointResult.class, sensr_proto.PointCloudOuterClass.PointResult.Builder.class);
      }

      // Construct using sensr_proto.PointCloudOuterClass.PointResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
        } else {
          points_ = null;
          pointsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sensr_proto.PointCloudOuterClass.internal_static_sensr_proto_PointResult_descriptor;
      }

      @java.lang.Override
      public sensr_proto.PointCloudOuterClass.PointResult getDefaultInstanceForType() {
        return sensr_proto.PointCloudOuterClass.PointResult.getDefaultInstance();
      }

      @java.lang.Override
      public sensr_proto.PointCloudOuterClass.PointResult build() {
        sensr_proto.PointCloudOuterClass.PointResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sensr_proto.PointCloudOuterClass.PointResult buildPartial() {
        sensr_proto.PointCloudOuterClass.PointResult result = new sensr_proto.PointCloudOuterClass.PointResult(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(sensr_proto.PointCloudOuterClass.PointResult result) {
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
      }

      private void buildPartial0(sensr_proto.PointCloudOuterClass.PointResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uid_ = uid_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sensr_proto.PointCloudOuterClass.PointResult) {
          return mergeFrom((sensr_proto.PointCloudOuterClass.PointResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sensr_proto.PointCloudOuterClass.PointResult other) {
        if (other == sensr_proto.PointCloudOuterClass.PointResult.getDefaultInstance()) return this;
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sensr_proto.PointCloudOuterClass.PointResult.PointCloud m =
                    input.readMessage(
                        sensr_proto.PointCloudOuterClass.PointResult.PointCloud.parser(),
                        extensionRegistry);
                if (pointsBuilder_ == null) {
                  ensurePointsIsMutable();
                  points_.add(m);
                } else {
                  pointsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 1610: {
                uid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 1610
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<sensr_proto.PointCloudOuterClass.PointResult.PointCloud> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          points_ = new java.util.ArrayList<sensr_proto.PointCloudOuterClass.PointResult.PointCloud>(points_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          sensr_proto.PointCloudOuterClass.PointResult.PointCloud, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder, sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder> pointsBuilder_;

      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public java.util.List<sensr_proto.PointCloudOuterClass.PointResult.PointCloud> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public sensr_proto.PointCloudOuterClass.PointResult.PointCloud getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder setPoints(
          int index, sensr_proto.PointCloudOuterClass.PointResult.PointCloud value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder setPoints(
          int index, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder addPoints(sensr_proto.PointCloudOuterClass.PointResult.PointCloud value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder addPoints(
          int index, sensr_proto.PointCloudOuterClass.PointResult.PointCloud value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder addPoints(
          sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder addPoints(
          int index, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends sensr_proto.PointCloudOuterClass.PointResult.PointCloud> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public java.util.List<? extends sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder> 
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            sensr_proto.PointCloudOuterClass.PointResult.PointCloud.getDefaultInstance());
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.getDefaultInstance());
      }
      /**
       * <code>repeated .sensr_proto.PointResult.PointCloud points = 1;</code>
       */
      public java.util.List<sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder> 
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          sensr_proto.PointCloudOuterClass.PointResult.PointCloud, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder, sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              sensr_proto.PointCloudOuterClass.PointResult.PointCloud, sensr_proto.PointCloudOuterClass.PointResult.PointCloud.Builder, sensr_proto.PointCloudOuterClass.PointResult.PointCloudOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 201;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 201;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 201;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 201;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        uid_ = getDefaultInstance().getUid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 201;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensr_proto.PointResult)
    }

    // @@protoc_insertion_point(class_scope:sensr_proto.PointResult)
    private static final sensr_proto.PointCloudOuterClass.PointResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sensr_proto.PointCloudOuterClass.PointResult();
    }

    public static sensr_proto.PointCloudOuterClass.PointResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PointResult>
        PARSER = new com.google.protobuf.AbstractParser<PointResult>() {
      @java.lang.Override
      public PointResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PointResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PointResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sensr_proto.PointCloudOuterClass.PointResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensr_proto_PointResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensr_proto_PointResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensr_proto_PointResult_PointCloud_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensr_proto_PointResult_PointCloud_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7lidarws/src/main/resource/sensr_proto/" +
      "point_cloud.proto\022\013sensr_proto\"\377\001\n\013Point" +
      "Result\0223\n\006points\030\001 \003(\0132#.sensr_proto.Poi" +
      "ntResult.PointCloud\022\014\n\003uid\030\311\001 \001(\t\032\254\001\n\nPo" +
      "intCloud\0226\n\004type\030\001 \001(\0162(.sensr_proto.Poi" +
      "ntResult.PointCloud.Type\022\n\n\002id\030\002 \001(\t\022\016\n\006" +
      "points\030\003 \001(\014\022\023\n\013intensities\030\004 \001(\014\"5\n\004Typ" +
      "e\022\010\n\004NONE\020\000\022\n\n\006GROUND\020\001\022\016\n\nBACKGROUND\020\002\022" +
      "\007\n\003RAW\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sensr_proto_PointResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensr_proto_PointResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensr_proto_PointResult_descriptor,
        new java.lang.String[] { "Points", "Uid", });
    internal_static_sensr_proto_PointResult_PointCloud_descriptor =
      internal_static_sensr_proto_PointResult_descriptor.getNestedTypes().get(0);
    internal_static_sensr_proto_PointResult_PointCloud_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensr_proto_PointResult_PointCloud_descriptor,
        new java.lang.String[] { "Type", "Id", "Points", "Intensities", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
